// One-off dev tool: extract the icons we use from the eunifyer icon set and
// vendor them into src/components/icons.generated.ts (committed, so CI needs no
// access to the eunifyer repo). Re-run locally if the icon set changes.
//
//   node scripts/extract-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SRC = "/Users/edihasaj/Projects/eunifyer/eunify/frontend/src/components/icons";

// map: our name -> eunifyer file
const MAP = {
  mcp: "gear",
  a2a: "share-all-right",
  memory: "artificial-intelligence",
  rides: "webhook",
  ops: "list",
  record: "file-text",
  incremental: "chart-trend-up",
  files: "docs",
  sql: "database",
  vector: "grid",
  recall: "refresh",
  agentfiles: "notes",
  vaults: "folder",
  bridge: "share-right",
  temporal: "clock",
  signed: "shield-check",
  injection: "shield",
  consent: "lock",
};

const CAMEL = [
  "strokeWidth", "strokeLinecap", "strokeLinejoin", "strokeMiterlimit",
  "strokeDasharray", "strokeDashoffset", "strokeOpacity",
  "fillRule", "clipRule", "fillOpacity", "clipPath",
];

function kebab(s) {
  return s.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
}

function extract(file) {
  const raw = readFileSync(join(SRC, file + ".tsx"), "utf8");
  const vb = (raw.match(/viewBox="([^"]+)"/) || [])[1] || "0 0 24 24";
  let body = (raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/) || [])[1] || "";

  body = body
    .replace(/<title>[\s\S]*?<\/title>/g, "")
    .replace(/\{title\}/g, "")
    // JSX color/size expressions -> concrete, themeable values
    .replace(/(fill|stroke)=\{fill\}/g, '$1="currentColor"')
    .replace(/(fill|stroke)=\{secondaryfill[^}]*\}/g, '$1="currentColor"')
    .replace(/strokeWidth=\{strokewidth\}/g, 'strokeWidth="1.6"')
    .replace(/(width|height)=\{[^}]*\}/g, "")
    .replace(/\{\.\.\.props\}/g, "")
    .replace(/data-color="[^"]*"/g, "")
    // any leftover JSX expression attribute -> drop
    .replace(/\s[a-zA-Z-]+=\{[^}]*\}/g, "");

  for (const c of CAMEL) body = body.replaceAll(c + "=", kebab(c) + "=");

  // normalize self-closing + whitespace
  body = body.replace(/\s+/g, " ").replace(/>\s+</g, "><").trim();
  return { vb, body };
}

const out = {};
for (const [name, file] of Object.entries(MAP)) out[name] = extract(file);

const ts =
  "// AUTO-GENERATED by scripts/extract-icons.mjs from the eunifyer icon set.\n" +
  "// Do not edit by hand; re-run the script to refresh.\n" +
  "export type IconName = " +
  Object.keys(out).map((n) => JSON.stringify(n)).join(" | ") + ";\n\n" +
  "export const ICONS: Record<IconName, { vb: string; body: string }> = " +
  JSON.stringify(out, null, 2) + ";\n";

writeFileSync(new URL("../src/components/icons.generated.ts", import.meta.url), ts);
console.log("wrote src/components/icons.generated.ts with", Object.keys(out).length, "icons");
